helmDefaults:
  historyMax: 3
  timeout: 1200
bases:
  - ./partial/environments.yaml
  - ./partial/repos.yaml


---
releases:
  - name: local-path-provisioner
    condition: local-path-provisioner.enabled
    chart: ./charts/local-path-provisioner
    namespace: local-path-storage
    createNamespace: true
    values:
      - ./charts/local-path-provisioner/values-default.yaml
    labels:
      group: init

  - name: init-db-env
    condition: database-env.enabled
    chart: ./charts/init-db-env
    namespace: database
    createNamespace: true
    values:
      - ./charts/init-db-env/values-default.yaml
    labels:
      group: database

  - name: postgres-operator
    condition: postgresql.enabled
    chart: cnpg/cloudnative-pg
    namespace:  database
    createNamespace: true
    values:
      - ./environments/{{ .Environment.Name }}/postgres-operator.yaml
    labels:
      group: database

  - name: postgres-cluster
    condition: postgresql.enabled
    chart: cnpg/cluster
    namespace: database
    createNamespace: true
    values:
      - ./environments/{{ .Environment.Name }}/postgres.yaml
    labels:
      group: database
    needs:
      - init-db-env
      - postgres-operator

  - name: mariadb-operator-crds
    condition: mariadb.enabled
    chart: mariadb-operator/mariadb-operator-crds
    namespace: database
    createNamespace: true
    labels:
      group: database

  - name: mariadb-operator
    condition: mariadb.enabled
    chart: mariadb-operator/mariadb-operator
    namespace: database
    createNamespace: true
    values:
      - ./environments/{{ .Environment.Name }}/mariadb-operator.yaml
    labels:
      group: database

  - name: mariadb-cluster
    condition: mariadb.enabled
    chart: mariadb-operator/mariadb-cluster
    namespace: database
    createNamespace: true
    values:
      - ./environments/{{ .Environment.Name }}/mariadb.yaml
    labels:
      group: database

  - name: mysql-operator
    condition: mysql.enabled
    chart: mysql-operator/mysql-operator
    namespace: database
    createNamespace: true
    disableValidationOnInstall: true # Required for CRDs installation
    labels:
      group: database

  - name: mysql-cluster
    condition: mysql.enabled
    chart: mysql-operator/mysql-innodbcluster
    namespace: database
    createNamespace: true
    values:
      - ./environments/{{ .Environment.Name }}/mysql.yaml
    labels:
      group: database
    needs:
      - init-db-env
      - mysql-operator

  - name: redis-operator
    condition: redis.enabled
    chart: ot-helm/redis-operator
    namespace: database
    createNamespace: true
    disableValidationOnInstall: true
    values:
      - ./environments/{{ .Environment.Name }}/redis-operator.yaml.gotmpl
    labels:
      group: database

  - name: redis-standalone
    condition: redis.enabled
    chart: ot-helm/redis-standalone
    namespace: database
    createNamespace: true
    disableValidationOnInstall: true
    values:
      - ./environments/{{ .Environment.Name }}/redis-standalone.yaml.gotmpl
    labels:
      group: databse
    needs:
      - redis-operator



  - name: cassandra-operator
    condition: cassandra.enabled
    chart: k8ssandra/k8ssandra-operator
    namespace: database
    createNamespace: true
    disableValidationOnInstall: true
    values:
      - ./environments/{{ .Environment.Name }}/cassandra-operator.yaml
    labels:
      group: database

