helmDefaults:
  historyMax: 3
  timeout: 1200
bases:
  - ./partial/environments.yaml
  - ./partial/repos.yaml


---
releases:
  - name: local-path-provisioner
    condition: local-path-provisioner.enabled
    chart: ./charts/local-path-provisioner
    namespace: local-path-storage
    createNamespace: true
    values:
      - ./charts/local-path-provisioner/values-default.yaml
    labels:
      group: init

  - name: postgres-operator
    condition: postgres.enabled
    chart: cnpg/cloudnative-pg
    namespace: database
    createNamespace: true
    values:
      - ""
    labels:
      group: database
    needs:
      - init
