apiVersion: v2
name: base-template
description: A Helm chart for Kubernetes with helm named templates
type: library

version: 0.1.1

keywords:
  - deployment
  - configmap
  - secret
  - HorizontalPodAutoscaler
  - hpa
  - VerticalPodAutoscaler
  - podDisruptionBudget
  - service
  - ingress
  - storageClass
  - pvc
