environments:
  dev:
    values:
      - local-path-provisioner:
          enabled: true
      - database-env:
          enabled: true
      - postgresql:
          enabled: true
      - mariadb:
          enabled: true
      - mysql:
          enabled: true
      - cassandra:
          enabled: true
      - redis:
          enabled: true
          namespace: database
          operator:
            version: v0.20.2
      - keycloak:
          enabled: true
          namespace: external-dev
          version: 26.3.2
