environments:
  dev:
    values:
      - local-path-provisioner:
          enabled: true
      - database-env:
          enabled: true
      - postgresql:
          enabled: true
      - mariadb:
          enabled: true
      - mysql:
          enabled: true