environments:
  dev:
    values:
      - ./environments/dev/default.yaml
      - local-path-provisioner:
          enabled: true
      - cert-manager:
          enabled: true
      - database-env:
          enabled: true
      - postgresql:
          enabled: true
      - mariadb:
          enabled: true
      - mysql:
          enabled: true
      - cassandra:
          enabled: true
          namespace: database
      - redis:
          enabled: true
          namespace: database
          operator:
            version: v0.20.2
      - keycloak:
          enabled: true
          namespace: infrastructure
          version: 26.3.2
      - emqx:
          enabled: true
          namespace: infrastructure
